services:

  DeadIt:
    build:
      context: ./DeadIt  
      dockerfile: Dockerfile
    image: deadit-deadit
    ports:
      - "7525:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  DeadIt-ContentCreation:
    build:
     context: ./DeatIt-CreationContentService
     dockerfile: Dockerfile
    image: deadit-deadit-content-creation
    ports:
     - "7526:8080"
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
