global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'deadit-main'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['DeadIt:80']
        labels:
          service: 'DeadIt'
          environment: 'development'

  - job_name: 'deadit-content-creation'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['DeadIt-ContentCreation:8080']
        labels:
          service: 'DeadIt-ContentCreation'
          environment: 'development'

