{
 "title": "DeadIt",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Состояние сервисов",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Состояние БД",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "database_connection_status{database=\"DeadIt\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Использование ОЗУ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "dotnet_total_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "process_num_threads", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Очистка GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "calls/min" } },
   "targets": [
    {
     "expr": "sum(rate(dotnet_collection_count_total[5m])) by (generation) * 60",
     "legendFormat": "Generation {{generation}}"
    }
   ]
  },
  {
   "title": "запуски Garbage Collect",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dotnet_collection_count_total) by (generation)",
     "legendFormat": "Generation {{generation}}"
    }
   ]
  },
  {
   "title": "Http requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count[5m]) * 600",
     "legendFormat": "{{method}} {{route}} {{code}}"
    }
   ]
  }
 ]
}