apiVersion: 1

contactPoints:
  - name: Telegram
    receivers:
      - uid: telegram-receiver
        type: telegram
        settings:
          bottoken: "8466585924:AAF1vwzEuxcGO-1OjvuISUo5avO9UrvLM6A"
          chatid: "-5008075700"
          disableResolveMessage: false

